### ISSUE TITLE
[Suggestion] New Logo For GPS Texter

### ISSUE THREAD

**Issue by zularizal** [syrop/GPS-Texter#1]
Hello @syrop  , I want to contribute to this project, I want to design a new logo for this project and it's free, do you want it?

**Comment by syrop** [comment]
Hi @zularizal, thanks you for your offer. GPS Texter is one of the very few projects I have designed an icon for on my own, and I am happy with this. Please stick around for the project called Viktor-Events. I lost a job, and I am working on my demo projects now, so unless my situation changes, 'Events' should go to production in a couple of weeks. Please open a new issue in that project if you are interested in helping.

I appreciate your help in Wiktor-Navigator. The icon you've made for that project is already in production.
